// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/topinambur02/url-shortener/internal/model"
)

// StoreRepository is an autogenerated mock type for the StoreRepository type
type StoreRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, url
func (_m *StoreRepository) Create(ctx context.Context, url model.URL) (*model.URL, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.URL) (*model.URL, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.URL) *model.URL); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.URL) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByShortURL provides a mock function with given fields: ctx, shortURL
func (_m *StoreRepository) GetByShortURL(ctx context.Context, shortURL string) (*model.URL, error) {
	ret := _m.Called(ctx, shortURL)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortURL")
	}

	var r0 *model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.URL, error)); ok {
		return rf(ctx, shortURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.URL); ok {
		r0 = rf(ctx, shortURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStoreRepository creates a new instance of StoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreRepository {
	mock := &StoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
