// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/topinambur02/url-shortener/internal/model"
)

// UrlRepository is an autogenerated mock type for the UrlRepository type
type UrlRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, url
func (_m *UrlRepository) Create(ctx context.Context, url model.Url) (*model.Url, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Url) (*model.Url, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Url) *model.Url); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Url)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Url) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByShortUrl provides a mock function with given fields: ctx, short_url
func (_m *UrlRepository) GetByShortUrl(ctx context.Context, short_url string) (*model.Url, error) {
	ret := _m.Called(ctx, short_url)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortUrl")
	}

	var r0 *model.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Url, error)); ok {
		return rf(ctx, short_url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Url); ok {
		r0 = rf(ctx, short_url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Url)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, short_url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUrlRepository creates a new instance of UrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlRepository {
	mock := &UrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
