// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/topinambur02/url-shortener/internal/dto"
)

// URLService is an autogenerated mock type for the URLService type
type URLService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, createURLDto, address
func (_m *URLService) Create(ctx context.Context, createURLDto *dto.CreateURLDto, address string) (*dto.ShortURLDto, error) {
	ret := _m.Called(ctx, createURLDto, address)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.ShortURLDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateURLDto, string) (*dto.ShortURLDto, error)); ok {
		return rf(ctx, createURLDto, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateURLDto, string) *dto.ShortURLDto); ok {
		r0 = rf(ctx, createURLDto, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ShortURLDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateURLDto, string) error); ok {
		r1 = rf(ctx, createURLDto, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByShortURL provides a mock function with given fields: ctx, shortURL
func (_m *URLService) GetByShortURL(ctx context.Context, shortURL string) (*dto.OriginalURLDto, error) {
	ret := _m.Called(ctx, shortURL)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortURL")
	}

	var r0 *dto.OriginalURLDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.OriginalURLDto, error)); ok {
		return rf(ctx, shortURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.OriginalURLDto); ok {
		r0 = rf(ctx, shortURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OriginalURLDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLService creates a new instance of URLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLService {
	mock := &URLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
