// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/topinambur02/url-shortener/internal/dto"
)

// UrlService is an autogenerated mock type for the UrlService type
type UrlService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, createUrlDto
func (_m *UrlService) Create(ctx context.Context, createUrlDto *dto.CreateUrlDto) (*dto.ShortUrlDto, error) {
	ret := _m.Called(ctx, createUrlDto)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.ShortUrlDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateUrlDto) (*dto.ShortUrlDto, error)); ok {
		return rf(ctx, createUrlDto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateUrlDto) *dto.ShortUrlDto); ok {
		r0 = rf(ctx, createUrlDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ShortUrlDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateUrlDto) error); ok {
		r1 = rf(ctx, createUrlDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByShortUrl provides a mock function with given fields: ctx, shortUrl
func (_m *UrlService) GetByShortUrl(ctx context.Context, shortUrl string) (*dto.OriginalUrlDto, error) {
	ret := _m.Called(ctx, shortUrl)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortUrl")
	}

	var r0 *dto.OriginalUrlDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.OriginalUrlDto, error)); ok {
		return rf(ctx, shortUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.OriginalUrlDto); ok {
		r0 = rf(ctx, shortUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OriginalUrlDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUrlService creates a new instance of UrlService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlService {
	mock := &UrlService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
